base_root_ssh_keys: []

base_root_yubikeys: []

base_users:
  - username: root
    authorized_keys:
      - "{{ base_root_ssh_keys }}"
      - "{{ extra_root_ssh_keys }}"
    authorized_yubikeys:
      - "{{ base_root_yubikeys }}"
      - "{{ extra_root_yubikeys }}"
  - username: ansible
    group: root
    authorized_keys:
      - ansible
    shell: /bin/bash

extra_users: []
